/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Lexer.TokenType;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

public class Compiler {
    public static void main(String[] args) {

        // This part is present for testing the first part of the project which is the lexer
        if (args.length >= 2 && args[0].equals("-lexer")) {
            String filePath = args[1];
            try (Reader reader = new BufferedReader(new FileReader(filePath))) {//buffered to read tokens in advance
                Lexer lexer = new Lexer(reader);
                Symbol symbol;
                do {
                    symbol = lexer.getNextSymbol();
                    System.out.println(symbol);
                } while (symbol.getType() != TokenType.EOF);
            } catch(IOException e) {
                System.err.println("Error reading file: " + e.getMessage());
                System.exit(1);
            } catch(RuntimeException e) {
                System.err.println("Lexing error: " + e.getMessage());
                System.exit(1);
            }
        } else {
            System.out.println("Usage: -lexer <input.lang>");
        }
    }
}
